### ISSUE TITLE
ArtificerExtended Mod Incompatibility

### ISSUE THREAD

**Issue by BellaRoka** [FMRadio11/ENV_Toggle#1]
The latest updates to [ArtificerExtended](https://thunderstore.io/package/duckduckgreyduck/ArtificerExtended/) seems to have broken this mod, and the toggle function no longer works as long as ArtificerExtended is installed.

**Comment by FMRadio11** [comment]
Hopefully fixed in 1.1.0 update - the way ArtificerExtended implements its passive slot overrides the hook that I use to inject the rewritten character main, so ENV Toggle now adds in a replacement passive and disables the hook if the mod is found. This will prevent ArtificerExtended from altering hover's character main when ENV Toggle is active, but the current version doesn't do that so nothing should break AFAIK.

**Comment by BellaRoka** [comment]
Thanks for the update! Gave it a spin and it seems to have fixed things.

One thing to note though is it seems the "Auto Surge" config option still doesn't function with ArtificerExtended installed (it did work prior to the update that also broke the jetpack toggle), even with ArtificerExtended's ion surge rework disabled in it's configs (it does work just fine with ArtificerExtended disabled). Not the biggest deal in the world if that can't be fixed.

Will also provide an update once I've done some testing in multiplayer to let you know if everything is working smoothly there.

Thanks again for taking the time to update!
